### ISSUE TITLE
Support non-blocking /run

### ISSUE THREAD

**Issue by pflueras** [pflueras/robbie9-2020#25]
/run endpoint blocks now for the entire journey of robbie9.
Implement non-blocking (multithreading?) behaviour.

**Comment by dd-iuonac** [comment]
Is it enough to implement just the multithreading behaviour?
Shall I create the CarService and the EventProcessor also?

**Comment by pflueras** [comment]
We can implement multithreading in a new CarService class (separation of concerns).
It's enough to implement just multithreading.
Stopping gracefully the car is also a big enough challenge (see #26).

**Comment by dd-iuonac** [comment]
How many cars could be managed by CarService?

**Comment by pflueras** [comment]
Only one car!

**Comment by dd-iuonac** [comment]
Where does CarService should be placed? In car or service package?
